before_build:
- ps: |
      Write-Host "> dotnet restore"

      dotnet restore -v m

      Write-Host "< dotnet restore"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

build_script:
- ps: |
      Write-Host "> dotnet build"

      dotnet build -c Release -v m 

      Write-Host "< dotnet build"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }