os: Visual Studio 2017

configuration: Release

environment:
  CODECOV_UPLOAD_TOKEN:
    secure: A6EfLnTXlaU17jh59qdcU9dQ7Svr9VVtS7If+Q4WdDh78msCxrf0hWELPY/7W/sz

version: 1.0.0

dotnet_csproj:
  patch: true
  file: 'src\$(appveyor_project_name)\$(appveyor_project_name).csproj'
  version: '{version}'

before_build:
- ps: |
      Write-Host "> dotnet restore"

      dotnet restore -v m

      Write-Host "< dotnet restore"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

build_script:
- ps: |
      Write-Host "> dotnet build"

      dotnet build -c $env:CONFIGURATION --no-restore -v m

      Write-Host "< dotnet build"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

after_build:
- ps: |
      Write-Host "> sn.exe"

      $sn = "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7 Tools\sn.exe"

      foreach ($assembly in ls "src\$env:APPVEYOR_PROJECT_NAME\bin\$env:CONFIGURATION\*\$env:APPVEYOR_PROJECT_NAME.dll") {
          &$sn -vf $assembly

          if ($LastExitCode -ne 0) { Break }
      }

      Write-Host "< sn.exe"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

      Write-Host "> dotnet pack"

      dotnet pack src\$env:APPVEYOR_PROJECT_NAME -c $env:CONFIGURATION --no-restore --no-build --include-symbols --output ..\..\artifacts -v m

      Write-Host "< dotnet pack"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

test_script:
- ps: |
      Write-Host "> dotnet test"

      dotnet test test\$env:APPVEYOR_PROJECT_NAME.Tests -c $env:CONFIGURATION --no-build -v m

      Write-Host "< dotnet test"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

after_test:
- ps: |
      Write-Host "> codecov"

      dotnet build -c $env:CONFIGURATION -v m /p:codecov=true

      choco install opencover.portable
      choco install codecov

      OpenCover.Console.exe -target:"$env:xunit20\xunit.console.x86.exe" -targetargs:"test\$env:APPVEYOR_PROJECT_NAME.Tests\bin\$env:CONFIGURATION\net471\$env:APPVEYOR_PROJECT_NAME.Tests.dll -noshadow" -register:user -filter:"+[*]* -[$env:APPVEYOR_PROJECT_NAME.Tests]*" -hideskipped:All -output:".\coverage.xml"
      codecov -f coverage.xml -t $env:CODECOV_UPLOAD_TOKEN

      Write-Host "< codecov"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

artifacts:
  - path: artifacts\$(appveyor_project_name).$(appveyor_build_version).nupkg
  - path: artifacts\$(appveyor_project_name).$(appveyor_build_version).symbols.nupkg
